<?php

namespace AppBundle\Repository;

use AppBundle\Entity\File;
use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    public function remove(File $file)
    {
        $this->getEntityManager()->remove($file);
        $this->getEntityManager()->flush();
    }
}
