<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Login;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * salvar login no banco
     *
     * @param Login $login
     * @return Login
     */
    public function save(Login $login)
    {
        $this->getEntityManager()->persist($login);
        $this->getEntityManager()->flush();

        return $login;
    }
}
