<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TaticRel;
use Doctrine\ORM\EntityRepository;

/**
 * TaticRelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaticRelRepository extends EntityRepository
{
}
