<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Users;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * salvar usuário no banco
     *
     * @param Users $user
     * @return Users
     */
    public function save(Users $user)
    {
        $this->getEntityManager()->persist($user);
        $this->getEntityManager()->flush();

        return $user;
    }
}
