tactician:
  commandbus:
      default:
          middleware:
              - tactician.middleware.locking
              - tactician.middleware.validator
              - tactician.middleware.command_handler
      transactional:
          middleware:
              - tactician.middleware.locking
              - AppBundle\Middleware\ReleaseRecordedEventsMiddleware
              - tactician.middleware.doctrine
              - tactician.middleware.validator
              - tactician.middleware.command_handler