# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
  #parameter_name: value
services:
  app.friend-tat.handler.create_friend_tat:
      class: AppBundle\Services\FriendTat\Handler\CreateFriendTatHandler
      arguments:
          - '@doctrine.orm.entity_manager'
          - '@event_recorder'
          - '@event_dispatcher'
      tags:
          - { name: tactician.handler, command: AppBundle\Services\FriendTat\Command\CreateFriendTatCommand }

  app.friend-tat.handler.update_friend_tat:
      class: AppBundle\Services\FriendTat\Handler\UpdateFriendTatHandler
      arguments:
          - '@doctrine.orm.entity_manager'
      tags:
          - { name: tactician.handler, command: AppBundle\Services\FriendTat\Command\UpdateFriendTatCommand }

  app.friend-tat.handler.delete_friend_tat:
      class: AppBundle\Services\FriendTat\Handler\DeleteFriendTatHandler
      arguments:
          - '@doctrine.orm.entity_manager'
      tags:
          - { name: tactician.handler, command: AppBundle\Services\FriendTat\Command\DeleteFriendTatCommand }



  app.tatic-rel.handler.create_tatic_rel:
      class: AppBundle\Services\TaticRel\Handler\CreateTaticRelHandler
      arguments:
          - '@doctrine.orm.entity_manager'
      tags:
          - { name: tactician.handler, command: AppBundle\Services\TaticRel\Command\CreateTaticRelCommand }

  app.tatic-rel.handler.update_tatic_rel:
      class: AppBundle\Services\TaticRel\Handler\UpdateTaticalRelHandler
      arguments:
          - '@doctrine.orm.entity_manager'
      tags:
          - { name: tactician.handler, command: AppBundle\Services\TaticRel\Command\UpdateTaticRelCommand }

  app.tatic-rel.handler.delete_tatic_rel:
      class: AppBundle\Services\TaticRel\Handler\DeleteFriendTatHandler
      arguments:
          - '@doctrine.orm.entity_manager'
      tags:
          - { name: tactician.handler, command: AppBundle\Services\TaticRel\Command\DeleteTaticRelCommand }