default:
    type: rest
    resource: "@AppBundle/Controller/DefaultController.php"

friend:
    type: rest
    resource: "@AppBundle/Controller/FriendController.php"

file:
    type: rest
    resource: "@AppBundle/Controller/FileController.php"